/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupo.view;

/**
 *
 * @author ccolome
 */
public class productoH extends javax.swing.JFrame {

    /**
     * Creates new form productoH
     */
    public productoH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detalleProductoHPanel = new javax.swing.JPanel();
        detallePHTituloLabel = new javax.swing.JLabel();
        detallePHOperacionLabel = new javax.swing.JLabel();
        detallePHoperacionTextField = new javax.swing.JTextField();
        detallePHCantidadSpinner = new javax.swing.JSpinner();
        detallePHCantidadJLabel = new javax.swing.JLabel();
        detallePHPrecioUSpinner = new javax.swing.JSpinner();
        detallePHPrecioULabel = new javax.swing.JLabel();
        detalleRegistrarPHButton = new javax.swing.JButton();
        detalleProductoHValidacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        detallePHTituloLabel.setText("Nuevo ingreso de stock");

        detallePHOperacionLabel.setText("Operación:");

        detallePHoperacionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallePHoperacionTextFieldActionPerformed(evt);
            }
        });

        detallePHCantidadSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        detallePHCantidadJLabel.setText("Cantidad:");

        detallePHPrecioUSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        detallePHPrecioULabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detallePHPrecioULabel.setText("<html><body>Precio<br>unitario:</body></html>");

        detalleRegistrarPHButton.setText("Registrar");
        detalleRegistrarPHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleRegistrarPHButtonActionPerformed(evt);
            }
        });

        detalleProductoHValidacionLabel.setBackground(new java.awt.Color(255, 0, 0));
        detalleProductoHValidacionLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        detalleProductoHValidacionLabel.setForeground(new java.awt.Color(255, 0, 0));
        detalleProductoHValidacionLabel.setText("EL campo {} es obligatorio.");

        javax.swing.GroupLayout detalleProductoHPanelLayout = new javax.swing.GroupLayout(detalleProductoHPanel);
        detalleProductoHPanel.setLayout(detalleProductoHPanelLayout);
        detalleProductoHPanelLayout.setHorizontalGroup(
            detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalleProductoHPanelLayout.createSequentialGroup()
                .addGroup(detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalleProductoHPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detallePHTituloLabel)
                            .addGroup(detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(detalleProductoHPanelLayout.createSequentialGroup()
                                    .addComponent(detallePHPrecioULabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(detallePHPrecioUSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(detalleProductoHPanelLayout.createSequentialGroup()
                                    .addGroup(detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(detallePHOperacionLabel)
                                        .addComponent(detallePHCantidadJLabel))
                                    .addGap(18, 18, 18)
                                    .addGroup(detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(detallePHCantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(detallePHoperacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(detalleProductoHPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(detalleRegistrarPHButton))
                    .addGroup(detalleProductoHPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(detalleProductoHValidacionLabel)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        detalleProductoHPanelLayout.setVerticalGroup(
            detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalleProductoHPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detallePHTituloLabel)
                .addGap(37, 37, 37)
                .addGroup(detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detallePHOperacionLabel)
                    .addComponent(detallePHoperacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detallePHCantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detallePHCantidadJLabel))
                .addGap(18, 18, 18)
                .addGroup(detalleProductoHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detallePHPrecioUSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detallePHPrecioULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(detalleProductoHValidacionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detalleRegistrarPHButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detalleProductoHPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detalleProductoHPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detallePHoperacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallePHoperacionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detallePHoperacionTextFieldActionPerformed

    private void detalleRegistrarPHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleRegistrarPHButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleRegistrarPHButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productoH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productoH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productoH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productoH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productoH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detallePHCantidadJLabel;
    private javax.swing.JSpinner detallePHCantidadSpinner;
    private javax.swing.JLabel detallePHOperacionLabel;
    private javax.swing.JLabel detallePHPrecioULabel;
    private javax.swing.JSpinner detallePHPrecioUSpinner;
    private javax.swing.JLabel detallePHTituloLabel;
    private javax.swing.JTextField detallePHoperacionTextField;
    private javax.swing.JPanel detalleProductoHPanel;
    private javax.swing.JLabel detalleProductoHValidacionLabel;
    private javax.swing.JButton detalleRegistrarPHButton;
    // End of variables declaration//GEN-END:variables
}
