/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupo.view;

/**
 *
 * @author ccolome
 */
public class ProductoPrueba1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramed
     */
    public ProductoPrueba1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productoTabbedPane = new javax.swing.JTabbedPane();
        consultaPanel = new javax.swing.JPanel();
        consultaBuscarLabel = new javax.swing.JLabel();
        consultaBuscarTextField = new javax.swing.JTextField();
        nuevoProductoButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        productosTable = new javax.swing.JTable();
        detalleVerProductoButton = new javax.swing.JButton();
        registroPanel = new javax.swing.JPanel();
        nuevoProductoLabel = new javax.swing.JLabel();
        nuevoNombreTextField = new javax.swing.JTextField();
        nuevoNombreLabel = new javax.swing.JLabel();
        nuevoMarcaLabel = new javax.swing.JLabel();
        nuevoMarcaTextField = new javax.swing.JTextField();
        nuevoLineaLabel = new javax.swing.JLabel();
        nuevoLineaTextField = new javax.swing.JTextField();
        nuevoStockSpinner = new javax.swing.JSpinner();
        nuevoStockLabel = new javax.swing.JLabel();
        nuevoPrecioULabel = new javax.swing.JLabel();
        nuevoPrecioUSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        nuevoObservacionTextArea = new javax.swing.JTextArea();
        nuevoObservacionLabel = new javax.swing.JLabel();
        nuevoRegistrarButton = new javax.swing.JButton();
        nuevoCancelarButton = new javax.swing.JButton();
        nuevoValidacionLabel = new javax.swing.JLabel();
        detallePanel = new javax.swing.JPanel();
        detalleProductoLabel = new javax.swing.JLabel();
        detalleNombreLabel = new javax.swing.JLabel();
        detalleNombreTextField = new javax.swing.JTextField();
        detalleLineaTextField = new javax.swing.JTextField();
        detalleStockSpinner = new javax.swing.JSpinner();
        detalleMarcaTextField = new javax.swing.JTextField();
        detalleMarcaLabel = new javax.swing.JLabel();
        detallePrecioULabel = new javax.swing.JLabel();
        detallePrecioUSpinner = new javax.swing.JSpinner();
        detalleObservacionLabel = new javax.swing.JLabel();
        detalleLineaLabel = new javax.swing.JLabel();
        detalleStockLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        productoHTable = new javax.swing.JTable();
        detalleProductoHLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        detalleObservacionTextArea = new javax.swing.JTextArea();
        detalleAgregarPButton = new javax.swing.JButton();
        detalleEditarButton = new javax.swing.JButton();
        detalleSalirButton = new javax.swing.JButton();
        detalleValidacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productoTabbedPane.setMinimumSize(new java.awt.Dimension(620, 480));
        productoTabbedPane.setPreferredSize(new java.awt.Dimension(620, 480));

        consultaBuscarLabel.setText("Buscar :");

        consultaBuscarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBuscarTextFieldActionPerformed(evt);
            }
        });

        nuevoProductoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        nuevoProductoButton.setText("Nuevo");
        nuevoProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProductoButtonActionPerformed(evt);
            }
        });

        productosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripcion", "Marca", "Linea", "Precio", "Stock", "Creación", "Modificación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(productosTable);

        detalleVerProductoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        detalleVerProductoButton.setText("Producto N°");
        detalleVerProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleVerProductoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaPanelLayout = new javax.swing.GroupLayout(consultaPanel);
        consultaPanel.setLayout(consultaPanelLayout);
        consultaPanelLayout.setHorizontalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addComponent(consultaBuscarLabel)
                        .addGap(18, 18, 18)
                        .addComponent(consultaBuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detalleVerProductoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuevoProductoButton)))
                .addContainerGap())
        );
        consultaPanelLayout.setVerticalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPanelLayout.createSequentialGroup()
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consultaBuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultaBuscarLabel)))
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevoProductoButton)
                            .addComponent(detalleVerProductoButton))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productoTabbedPane.addTab("Consulta de productos", consultaPanel);

        nuevoProductoLabel.setText("Nuevo producto");

        nuevoNombreLabel.setText("Nombre:");

        nuevoMarcaLabel.setText("Marca:");

        nuevoLineaLabel.setText("Linea:");

        nuevoStockSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        nuevoStockLabel.setText("Stock:");

        nuevoPrecioULabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoPrecioULabel.setText("<html><body>Precio<br>unitario:</body></html>");

        nuevoPrecioUSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        nuevoObservacionTextArea.setColumns(20);
        nuevoObservacionTextArea.setRows(5);
        jScrollPane1.setViewportView(nuevoObservacionTextArea);

        nuevoObservacionLabel.setText("Observaciones:");

        nuevoRegistrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        nuevoRegistrarButton.setText("Registrar");
        nuevoRegistrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoRegistrarButtonActionPerformed(evt);
            }
        });

        nuevoCancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        nuevoCancelarButton.setText("Cancelar");
        nuevoCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCancelarButtonActionPerformed(evt);
            }
        });

        nuevoValidacionLabel.setBackground(new java.awt.Color(255, 0, 0));
        nuevoValidacionLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        nuevoValidacionLabel.setForeground(new java.awt.Color(255, 0, 0));
        nuevoValidacionLabel.setText("EL campo {} es obligatorio.");

        javax.swing.GroupLayout registroPanelLayout = new javax.swing.GroupLayout(registroPanel);
        registroPanel.setLayout(registroPanelLayout);
        registroPanelLayout.setHorizontalGroup(
            registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelLayout.createSequentialGroup()
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addComponent(nuevoProductoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoValidacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addComponent(nuevoPrecioULabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nuevoPrecioUSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nuevoMarcaLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addComponent(nuevoCancelarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nuevoRegistrarButton))
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(nuevoStockLabel)
                                .addGap(19, 19, 19)
                                .addComponent(nuevoStockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(nuevoObservacionLabel)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nuevoMarcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addComponent(nuevoNombreLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nuevoNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(nuevoLineaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoLineaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        registroPanelLayout.setVerticalGroup(
            registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoProductoLabel)
                    .addComponent(nuevoValidacionLabel))
                .addGap(32, 32, 32)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoNombreLabel)
                    .addComponent(nuevoNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoLineaLabel)
                    .addComponent(nuevoLineaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoMarcaLabel)
                    .addComponent(nuevoMarcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoStockLabel)
                    .addComponent(nuevoStockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoPrecioULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoPrecioUSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoObservacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nuevoCancelarButton)
                        .addComponent(nuevoRegistrarButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        productoTabbedPane.addTab("Registro de producto", registroPanel);

        detalleProductoLabel.setText(" Detalle producto : N° ");

        detalleNombreLabel.setText("Nombre:");

        detalleMarcaLabel.setText("Marca:");

        detallePrecioULabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detallePrecioULabel.setText("<html><body>Precio<br>unitario:</body></html>");

        detallePrecioUSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        detalleObservacionLabel.setText("Observaciones:");

        detalleLineaLabel.setText("Linea:");

        detalleStockLabel.setText("Stock:");

        productoHTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Operacion", "Cantidad", "Precio", "Creador", "Creación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productoHTable);

        detalleProductoHLabel.setText("Historial de operaciones:");

        detalleObservacionTextArea.setColumns(20);
        detalleObservacionTextArea.setRows(5);
        jScrollPane5.setViewportView(detalleObservacionTextArea);

        detalleAgregarPButton.setText("Agregar");
        detalleAgregarPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleAgregarPButtonActionPerformed(evt);
            }
        });

        detalleEditarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        detalleEditarButton.setToolTipText("Editar");
        detalleEditarButton.setMaximumSize(new java.awt.Dimension(55, 40));
        detalleEditarButton.setMinimumSize(new java.awt.Dimension(55, 40));
        detalleEditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleEditarButtonActionPerformed(evt);
            }
        });

        detalleSalirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        detalleSalirButton.setToolTipText("Salir");
        detalleSalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleSalirButtonActionPerformed(evt);
            }
        });

        detalleValidacionLabel.setBackground(new java.awt.Color(255, 0, 0));
        detalleValidacionLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        detalleValidacionLabel.setForeground(new java.awt.Color(255, 0, 0));
        detalleValidacionLabel.setText("EL campo {} es obligatorio.");

        javax.swing.GroupLayout detallePanelLayout = new javax.swing.GroupLayout(detallePanel);
        detallePanel.setLayout(detallePanelLayout);
        detallePanelLayout.setHorizontalGroup(
            detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallePanelLayout.createSequentialGroup()
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detallePanelLayout.createSequentialGroup()
                        .addComponent(detalleProductoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(detalleValidacionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detalleEditarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detalleSalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detallePanelLayout.createSequentialGroup()
                        .addComponent(detalleNombreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(detalleNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(detalleLineaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(detalleLineaTextField))
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detallePanelLayout.createSequentialGroup()
                                .addComponent(detallePrecioULabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(detallePrecioUSpinner))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detallePanelLayout.createSequentialGroup()
                                .addComponent(detalleMarcaLabel)
                                .addGap(30, 30, 30)
                                .addComponent(detalleMarcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(detalleStockLabel)
                        .addGap(18, 18, 18)
                        .addComponent(detalleStockSpinner))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detallePanelLayout.createSequentialGroup()
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addComponent(detalleObservacionLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addComponent(detalleProductoHLabel)
                                .addGap(88, 88, 88)
                                .addComponent(detalleAgregarPButton))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        detallePanelLayout.setVerticalGroup(
            detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(detalleProductoLabel)
                        .addComponent(detalleValidacionLabel))
                    .addComponent(detalleSalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleEditarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detalleNombreLabel)
                    .addComponent(detalleNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleLineaLabel)
                    .addComponent(detalleLineaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detalleMarcaLabel)
                    .addComponent(detalleMarcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleStockLabel)
                    .addComponent(detalleStockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detallePrecioULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detallePrecioUSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detalleObservacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleProductoHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleAgregarPButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap())
        );

        productoTabbedPane.addTab("Detalle de producto", detallePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productoTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productoTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaBuscarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBuscarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaBuscarTextFieldActionPerformed

    private void nuevoProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProductoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoProductoButtonActionPerformed

    private void nuevoRegistrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoRegistrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoRegistrarButtonActionPerformed

    private void nuevoCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoCancelarButtonActionPerformed

    private void detalleAgregarPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleAgregarPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleAgregarPButtonActionPerformed

    private void detalleEditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleEditarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleEditarButtonActionPerformed

    private void detalleSalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleSalirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleSalirButtonActionPerformed

    private void detalleVerProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleVerProductoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleVerProductoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoPrueba1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoPrueba1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoPrueba1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoPrueba1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoPrueba1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consultaBuscarLabel;
    private javax.swing.JTextField consultaBuscarTextField;
    private javax.swing.JPanel consultaPanel;
    private javax.swing.JButton detalleAgregarPButton;
    private javax.swing.JButton detalleEditarButton;
    private javax.swing.JLabel detalleLineaLabel;
    private javax.swing.JTextField detalleLineaTextField;
    private javax.swing.JLabel detalleMarcaLabel;
    private javax.swing.JTextField detalleMarcaTextField;
    private javax.swing.JLabel detalleNombreLabel;
    private javax.swing.JTextField detalleNombreTextField;
    private javax.swing.JLabel detalleObservacionLabel;
    private javax.swing.JTextArea detalleObservacionTextArea;
    private javax.swing.JPanel detallePanel;
    private javax.swing.JLabel detallePrecioULabel;
    private javax.swing.JSpinner detallePrecioUSpinner;
    private javax.swing.JLabel detalleProductoHLabel;
    private javax.swing.JLabel detalleProductoLabel;
    private javax.swing.JButton detalleSalirButton;
    private javax.swing.JLabel detalleStockLabel;
    private javax.swing.JSpinner detalleStockSpinner;
    private javax.swing.JLabel detalleValidacionLabel;
    private javax.swing.JButton detalleVerProductoButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton nuevoCancelarButton;
    private javax.swing.JLabel nuevoLineaLabel;
    private javax.swing.JTextField nuevoLineaTextField;
    private javax.swing.JLabel nuevoMarcaLabel;
    private javax.swing.JTextField nuevoMarcaTextField;
    private javax.swing.JLabel nuevoNombreLabel;
    private javax.swing.JTextField nuevoNombreTextField;
    private javax.swing.JLabel nuevoObservacionLabel;
    private javax.swing.JTextArea nuevoObservacionTextArea;
    private javax.swing.JLabel nuevoPrecioULabel;
    private javax.swing.JSpinner nuevoPrecioUSpinner;
    private javax.swing.JButton nuevoProductoButton;
    private javax.swing.JLabel nuevoProductoLabel;
    private javax.swing.JButton nuevoRegistrarButton;
    private javax.swing.JLabel nuevoStockLabel;
    private javax.swing.JSpinner nuevoStockSpinner;
    private javax.swing.JLabel nuevoValidacionLabel;
    private javax.swing.JTable productoHTable;
    private javax.swing.JTabbedPane productoTabbedPane;
    private javax.swing.JTable productosTable;
    private javax.swing.JPanel registroPanel;
    // End of variables declaration//GEN-END:variables
}
