/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupo.view;

/**
 *
 * @author ccolome
 */
public class UsuarioPrueba extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public UsuarioPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        principalToolBar = new javax.swing.JToolBar();
        productoButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        ventaButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        clienteButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        usuarioButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        salirButton = new javax.swing.JButton();
        componentePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principalPanel.setPreferredSize(new java.awt.Dimension(720, 480));

        principalToolBar.setFloatable(false);
        principalToolBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        principalToolBar.setRollover(true);
        principalToolBar.setToolTipText("");

        productoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos.png"))); // NOI18N
        productoButton.setText("Productos");
        productoButton.setFocusable(false);
        productoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        productoButton.setPreferredSize(new java.awt.Dimension(90, 95));
        productoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        productoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoButtonActionPerformed(evt);
            }
        });
        principalToolBar.add(productoButton);
        principalToolBar.add(jSeparator1);

        ventaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-al-carrito.png"))); // NOI18N
        ventaButton.setText("Ventas");
        ventaButton.setFocusable(false);
        ventaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ventaButton.setMaximumSize(new java.awt.Dimension(90, 95));
        ventaButton.setMinimumSize(new java.awt.Dimension(90, 95));
        ventaButton.setPreferredSize(new java.awt.Dimension(90, 95));
        ventaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ventaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaButtonActionPerformed(evt);
            }
        });
        principalToolBar.add(ventaButton);
        principalToolBar.add(jSeparator2);

        clienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        clienteButton.setText("Clientes");
        clienteButton.setFocusable(false);
        clienteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clienteButton.setMaximumSize(new java.awt.Dimension(90, 95));
        clienteButton.setPreferredSize(new java.awt.Dimension(90, 95));
        clienteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        principalToolBar.add(clienteButton);
        principalToolBar.add(jSeparator3);
        principalToolBar.add(filler2);

        usuarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vendedora.png"))); // NOI18N
        usuarioButton.setText("Usuarios");
        usuarioButton.setToolTipText("");
        usuarioButton.setFocusable(false);
        usuarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioButton.setMaximumSize(new java.awt.Dimension(90, 95));
        usuarioButton.setMinimumSize(new java.awt.Dimension(90, 95));
        usuarioButton.setPreferredSize(new java.awt.Dimension(90, 95));
        usuarioButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        principalToolBar.add(usuarioButton);
        principalToolBar.add(filler1);

        salirButton.setText("Salir");
        salirButton.setToolTipText("");
        salirButton.setFocusable(false);
        salirButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirButton.setMaximumSize(new java.awt.Dimension(90, 20));
        salirButton.setMinimumSize(new java.awt.Dimension(90, 20));
        salirButton.setPreferredSize(new java.awt.Dimension(90, 30));
        salirButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        principalToolBar.add(salirButton);

        javax.swing.GroupLayout componentePanelLayout = new javax.swing.GroupLayout(componentePanel);
        componentePanel.setLayout(componentePanelLayout);
        componentePanelLayout.setHorizontalGroup(
            componentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        componentePanelLayout.setVerticalGroup(
            componentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addComponent(principalToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(componentePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoButtonActionPerformed

    private void ventaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clienteButton;
    private javax.swing.JPanel componentePanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JToolBar principalToolBar;
    private javax.swing.JButton productoButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton usuarioButton;
    private javax.swing.JButton ventaButton;
    // End of variables declaration//GEN-END:variables
}
