/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupo.view;

/**
 *
 * @author ccolome
 */
public class UsuarioPrueba extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramed
     */
    public UsuarioPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteTabbedPane = new javax.swing.JTabbedPane();
        consultaPanel = new javax.swing.JPanel();
        consultaBuscarLabel = new javax.swing.JLabel();
        consultaBuscarTextField = new javax.swing.JTextField();
        nuevoUsuarioButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        usuariosTable = new javax.swing.JTable();
        detalleVerUsuarioButton = new javax.swing.JButton();
        registroPanel = new javax.swing.JPanel();
        nuevoUsuarioLabel = new javax.swing.JLabel();
        nuevoNombreTextField = new javax.swing.JTextField();
        nuevoNombreLabel = new javax.swing.JLabel();
        nuevoApellidoLabel = new javax.swing.JLabel();
        nuevoDireccionTextField = new javax.swing.JTextField();
        nuevoTIpoPersonaLabel = new javax.swing.JLabel();
        nuevoTipoDocULabel = new javax.swing.JLabel();
        nuevoRegistrarButton = new javax.swing.JButton();
        nuevoCancelarButton = new javax.swing.JButton();
        nuevoValidacionLabel = new javax.swing.JLabel();
        nuevoTipoDocJComboBox = new javax.swing.JComboBox<>();
        nuevoNumeroDocTextField = new javax.swing.JTextField();
        nuevoNumeroDocLabel = new javax.swing.JLabel();
        nuevoApellidoTextField = new javax.swing.JTextField();
        nuevoDIreccionLabel = new javax.swing.JLabel();
        nuevoTelefonoLabel = new javax.swing.JLabel();
        nuevotelefonoTextField = new javax.swing.JTextField();
        nuevoConfirmarPasslLabel = new javax.swing.JLabel();
        nuevoTipoPersonajComboBox = new javax.swing.JComboBox<>();
        nuevoNombreUsuarioLabel = new javax.swing.JLabel();
        nuevoNombreUsuarioTextField = new javax.swing.JTextField();
        nuevoConfirmarjPasswordField = new javax.swing.JPasswordField();
        nuevoContraseñaLabel = new javax.swing.JLabel();
        nuevoTIpoUsuarioLabel1 = new javax.swing.JLabel();
        nuevoTipoUsuariojComboBox = new javax.swing.JComboBox<>();
        nuevoEmailLabel = new javax.swing.JLabel();
        nuevoEmailTextField = new javax.swing.JTextField();
        nuevojPasswordField = new javax.swing.JPasswordField();
        detallePanel = new javax.swing.JPanel();
        detalleUsuarioLabel = new javax.swing.JLabel();
        detalleNombreLabel = new javax.swing.JLabel();
        detalleNombreTextField = new javax.swing.JTextField();
        detalleApellidoTextField = new javax.swing.JTextField();
        detalleMarcaLabel = new javax.swing.JLabel();
        detalleEditarButton = new javax.swing.JButton();
        detalleSalirButton = new javax.swing.JButton();
        detalleValidacionLabel = new javax.swing.JLabel();
        detalleTipoPersonajComboBox = new javax.swing.JComboBox<>();
        detalleTIpoPersonaLabel = new javax.swing.JLabel();
        detalleTipoDocULabel = new javax.swing.JLabel();
        detalleTipoDocJComboBox = new javax.swing.JComboBox<>();
        detalleNumeroDocLabel = new javax.swing.JLabel();
        detalleNombreUsuarioLabel = new javax.swing.JLabel();
        detalleNombreUsuarioTextField = new javax.swing.JTextField();
        detalleNumeroDocTextField = new javax.swing.JTextField();
        detalleTelefonoLabel = new javax.swing.JLabel();
        detalletelefonoTextField = new javax.swing.JTextField();
        detalleDIreccionLabel = new javax.swing.JLabel();
        detalleDireccionTextField = new javax.swing.JTextField();
        detalleEmailLabel = new javax.swing.JLabel();
        detalleEmailTextField = new javax.swing.JTextField();
        detalleConfirmarjPasswordField = new javax.swing.JPasswordField();
        detalleConfirmarPasslLabel = new javax.swing.JLabel();
        detallepassLabel = new javax.swing.JLabel();
        detallejPasswordField = new javax.swing.JPasswordField();
        detalleTIpoUsuarioLabel = new javax.swing.JLabel();
        detalleTipoUsuariojComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clienteTabbedPane.setMinimumSize(new java.awt.Dimension(620, 480));
        clienteTabbedPane.setPreferredSize(new java.awt.Dimension(620, 480));

        consultaBuscarLabel.setText("Buscar :");

        consultaBuscarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBuscarTextFieldActionPerformed(evt);
            }
        });

        nuevoUsuarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        nuevoUsuarioButton.setText("Nuevo");
        nuevoUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoUsuarioButtonActionPerformed(evt);
            }
        });

        usuariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Usuario", "Nombres", "Apellidos", "Num Doc.", "Creación", "Modificación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(usuariosTable);

        detalleVerUsuarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        detalleVerUsuarioButton.setText("Usuario N°");
        detalleVerUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleVerUsuarioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaPanelLayout = new javax.swing.GroupLayout(consultaPanel);
        consultaPanel.setLayout(consultaPanelLayout);
        consultaPanelLayout.setHorizontalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addComponent(consultaBuscarLabel)
                        .addGap(18, 18, 18)
                        .addComponent(consultaBuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detalleVerUsuarioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuevoUsuarioButton)))
                .addContainerGap())
        );
        consultaPanelLayout.setVerticalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPanelLayout.createSequentialGroup()
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consultaBuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultaBuscarLabel)))
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevoUsuarioButton)
                            .addComponent(detalleVerUsuarioButton))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clienteTabbedPane.addTab("Consulta de usuario", consultaPanel);

        nuevoUsuarioLabel.setText("Nuevo usuario");

        nuevoNombreLabel.setText("Nombre:");

        nuevoApellidoLabel.setText("Apellido:");

        nuevoTIpoPersonaLabel.setText("Tipo:");

        nuevoTipoDocULabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoTipoDocULabel.setText("<html><body>Tipo<br>documento:</body></html>");

        nuevoRegistrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        nuevoRegistrarButton.setText("Registrar");
        nuevoRegistrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoRegistrarButtonActionPerformed(evt);
            }
        });

        nuevoCancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        nuevoCancelarButton.setText("Cancelar");
        nuevoCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCancelarButtonActionPerformed(evt);
            }
        });

        nuevoValidacionLabel.setBackground(new java.awt.Color(255, 0, 0));
        nuevoValidacionLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        nuevoValidacionLabel.setForeground(new java.awt.Color(255, 0, 0));
        nuevoValidacionLabel.setText("EL campo {} es obligatorio.");

        nuevoTipoDocJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "RUC", "CE" }));

        nuevoNumeroDocLabel.setText("<html><body>Numero<br>documento:</body></html>");

        nuevoDIreccionLabel.setText("DIrección:");

        nuevoTelefonoLabel.setText("Teléfono:");

        nuevotelefonoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevotelefonoTextFieldActionPerformed(evt);
            }
        });

        nuevoConfirmarPasslLabel.setText("<html><body>Contraseña<br>confirmar:</body></html>");

        nuevoTipoPersonajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NATURAL", "JURIDICA" }));

        nuevoNombreUsuarioLabel.setText("<html><body>Nombre<br>de<br>Usuario:</body></html>");

        nuevoConfirmarjPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoConfirmarjPasswordFieldActionPerformed(evt);
            }
        });

        nuevoContraseñaLabel.setText("Contraseña:");

        nuevoTIpoUsuarioLabel1.setText("<html><body>Tipo<br>Usuario:</body></html>");

        nuevoTipoUsuariojComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VENDEDOR", "ALMACEN", "ADMINISTRADOR" }));

        nuevoEmailLabel.setText("Email:");

        javax.swing.GroupLayout registroPanelLayout = new javax.swing.GroupLayout(registroPanel);
        registroPanel.setLayout(registroPanelLayout);
        registroPanelLayout.setHorizontalGroup(
            registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelLayout.createSequentialGroup()
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addComponent(nuevoUsuarioLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoValidacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroPanelLayout.createSequentialGroup()
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nuevoApellidoLabel)
                                    .addComponent(nuevoNombreLabel))
                                .addGap(34, 34, 34)
                                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nuevoNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevoApellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(registroPanelLayout.createSequentialGroup()
                                    .addComponent(nuevoTelefonoLabel)
                                    .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(registroPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nuevoCancelarButton)
                                            .addGap(83, 83, 83))
                                        .addGroup(registroPanelLayout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nuevoDireccionTextField)
                                                .addComponent(nuevotelefonoTextField)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registroPanelLayout.createSequentialGroup()
                                    .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nuevoNumeroDocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nuevoDIreccionLabel)
                                        .addComponent(nuevoNombreUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nuevoNombreUsuarioTextField)
                                        .addComponent(nuevoNumeroDocTextField)))))
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(nuevoRegistrarButton))
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registroPanelLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nuevoTIpoUsuarioLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nuevoTipoDocULabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nuevoTIpoPersonaLabel))
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nuevoConfirmarPasslLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nuevoContraseñaLabel)
                                            .addComponent(nuevoEmailLabel))
                                        .addGap(18, 18, 18)))
                                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nuevoTipoDocJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevoTipoPersonajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevoEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevoTipoUsuariojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevojPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevoConfirmarjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        registroPanelLayout.setVerticalGroup(
            registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoUsuarioLabel)
                    .addComponent(nuevoValidacionLabel))
                .addGap(33, 33, 33)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevoTIpoPersonaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nuevoNombreLabel)
                                .addComponent(nuevoNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(nuevoTipoDocULabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nuevoApellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevoApellidoLabel)))))
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addComponent(nuevoTipoPersonajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoTipoDocJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(nuevoTIpoUsuarioLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevoNumeroDocTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoNumeroDocLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoTipoUsuariojComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nuevoNombreUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevotelefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoTelefonoLabel)
                            .addComponent(nuevoConfirmarPasslLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoConfirmarjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevoNombreUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoContraseñaLabel)
                            .addComponent(nuevojPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoDIreccionLabel)
                    .addComponent(nuevoDireccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoEmailLabel)
                    .addComponent(nuevoEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoCancelarButton)
                    .addComponent(nuevoRegistrarButton))
                .addGap(35, 35, 35))
        );

        clienteTabbedPane.addTab("Registro de usuario", registroPanel);

        detalleUsuarioLabel.setText(" Detalle usuario : N° ");

        detalleNombreLabel.setText("Nombre:");

        detalleApellidoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleApellidoTextFieldActionPerformed(evt);
            }
        });

        detalleMarcaLabel.setText("Apellido:");

        detalleEditarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        detalleEditarButton.setToolTipText("Editar");
        detalleEditarButton.setMaximumSize(new java.awt.Dimension(55, 40));
        detalleEditarButton.setMinimumSize(new java.awt.Dimension(55, 40));
        detalleEditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleEditarButtonActionPerformed(evt);
            }
        });

        detalleSalirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        detalleSalirButton.setToolTipText("Salir");
        detalleSalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleSalirButtonActionPerformed(evt);
            }
        });

        detalleValidacionLabel.setBackground(new java.awt.Color(255, 0, 0));
        detalleValidacionLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        detalleValidacionLabel.setForeground(new java.awt.Color(255, 0, 0));
        detalleValidacionLabel.setText("EL campo {} es obligatorio.");

        detalleTipoPersonajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NATURAL", "JURIDICA" }));

        detalleTIpoPersonaLabel.setText("Tipo:");

        detalleTipoDocULabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detalleTipoDocULabel.setText("<html><body>Tipo<br>documento:</body></html>");

        detalleTipoDocJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "RUC", "CE" }));

        detalleNumeroDocLabel.setText("<html><body>Numero<br>documento:</body></html>");

        detalleNombreUsuarioLabel.setText("<html><body>Nombre<br>de<br>Usuario:</body></html>");

        detalleTelefonoLabel.setText("Teléfono:");

        detalletelefonoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalletelefonoTextFieldActionPerformed(evt);
            }
        });

        detalleDIreccionLabel.setText("DIrección:");

        detalleEmailLabel.setText("Email:");

        detalleConfirmarjPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleConfirmarjPasswordFieldActionPerformed(evt);
            }
        });

        detalleConfirmarPasslLabel.setText("<html><body>Contraseña<br>confirmar:</body></html>");

        detallepassLabel.setText("Contraseña:");

        detalleTIpoUsuarioLabel.setText("<html><body>Tipo<br>Usuario:</body></html>");

        detalleTipoUsuariojComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VENDEDOR", "ALMACEN", "ADMINISTRADOR" }));

        javax.swing.GroupLayout detallePanelLayout = new javax.swing.GroupLayout(detallePanel);
        detallePanel.setLayout(detallePanelLayout);
        detallePanelLayout.setHorizontalGroup(
            detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallePanelLayout.createSequentialGroup()
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detallePanelLayout.createSequentialGroup()
                        .addComponent(detalleUsuarioLabel)
                        .addGap(18, 18, 18)
                        .addComponent(detalleValidacionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detalleEditarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detalleSalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detalleMarcaLabel)
                            .addComponent(detalleNombreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detalleTipoPersonajComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(detalleTipoDocJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addComponent(detalleTelefonoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(detalletelefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detalleNumeroDocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(detalleDIreccionLabel)
                                    .addComponent(detalleEmailLabel)
                                    .addComponent(detalleNombreUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detallePanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(detalleNumeroDocTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                            .addComponent(detalleApellidoTextField)
                                            .addComponent(detalleNombreTextField)
                                            .addComponent(detalleNombreUsuarioTextField)))
                                    .addGroup(detallePanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(detalleEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(detalleDireccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detallePanelLayout.createSequentialGroup()
                                        .addComponent(detalleTIpoUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(detallePanelLayout.createSequentialGroup()
                                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(detallepassLabel)
                                            .addComponent(detalleConfirmarPasslLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(detalleTipoUsuariojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(detalleConfirmarjPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(detallejPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detalleTIpoPersonaLabel)
                                    .addComponent(detalleTipoDocULabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        detallePanelLayout.setVerticalGroup(
            detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(detalleUsuarioLabel)
                        .addComponent(detalleValidacionLabel))
                    .addComponent(detalleSalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleEditarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detalleNombreLabel)
                                    .addComponent(detalleNombreTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detallePanelLayout.createSequentialGroup()
                                .addComponent(detalleTIpoPersonaLabel)
                                .addGap(16, 16, 16)))
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detalleMarcaLabel)
                            .addComponent(detalleApellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detalleTipoDocULabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addComponent(detalleTipoPersonajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(detalleTipoDocJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detalleTIpoUsuarioLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleNumeroDocTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleNumeroDocLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleTipoUsuariojComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(detalleNombreUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detalletelefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detalleTelefonoLabel)
                            .addComponent(detalleConfirmarPasslLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detalleConfirmarjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detalleNombreUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detallepassLabel)
                            .addComponent(detallejPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detalleDireccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleDIreccionLabel))
                .addGap(22, 22, 22)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detalleEmailLabel)
                    .addComponent(detalleEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        clienteTabbedPane.addTab("Detalle de usuario", detallePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clienteTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clienteTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaBuscarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBuscarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaBuscarTextFieldActionPerformed

    private void nuevoUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoUsuarioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoUsuarioButtonActionPerformed

    private void nuevoRegistrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoRegistrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoRegistrarButtonActionPerformed

    private void nuevoCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoCancelarButtonActionPerformed

    private void detalleVerUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleVerUsuarioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleVerUsuarioButtonActionPerformed

    private void nuevotelefonoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevotelefonoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevotelefonoTextFieldActionPerformed

    private void nuevoConfirmarjPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoConfirmarjPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoConfirmarjPasswordFieldActionPerformed

    private void detalleSalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleSalirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleSalirButtonActionPerformed

    private void detalleEditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleEditarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleEditarButtonActionPerformed

    private void detalleApellidoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleApellidoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleApellidoTextFieldActionPerformed

    private void detalletelefonoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalletelefonoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalletelefonoTextFieldActionPerformed

    private void detalleConfirmarjPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleConfirmarjPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleConfirmarjPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane clienteTabbedPane;
    private javax.swing.JLabel consultaBuscarLabel;
    private javax.swing.JTextField consultaBuscarTextField;
    private javax.swing.JPanel consultaPanel;
    private javax.swing.JTextField detalleApellidoTextField;
    private javax.swing.JLabel detalleConfirmarPasslLabel;
    private javax.swing.JPasswordField detalleConfirmarjPasswordField;
    private javax.swing.JLabel detalleDIreccionLabel;
    private javax.swing.JTextField detalleDireccionTextField;
    private javax.swing.JButton detalleEditarButton;
    private javax.swing.JLabel detalleEmailLabel;
    private javax.swing.JTextField detalleEmailTextField;
    private javax.swing.JLabel detalleMarcaLabel;
    private javax.swing.JLabel detalleNombreLabel;
    private javax.swing.JTextField detalleNombreTextField;
    private javax.swing.JLabel detalleNombreUsuarioLabel;
    private javax.swing.JTextField detalleNombreUsuarioTextField;
    private javax.swing.JLabel detalleNumeroDocLabel;
    private javax.swing.JTextField detalleNumeroDocTextField;
    private javax.swing.JPanel detallePanel;
    private javax.swing.JButton detalleSalirButton;
    private javax.swing.JLabel detalleTIpoPersonaLabel;
    private javax.swing.JLabel detalleTIpoUsuarioLabel;
    private javax.swing.JLabel detalleTelefonoLabel;
    private javax.swing.JComboBox<String> detalleTipoDocJComboBox;
    private javax.swing.JLabel detalleTipoDocULabel;
    private javax.swing.JComboBox<String> detalleTipoPersonajComboBox;
    private javax.swing.JComboBox<String> detalleTipoUsuariojComboBox;
    private javax.swing.JLabel detalleUsuarioLabel;
    private javax.swing.JLabel detalleValidacionLabel;
    private javax.swing.JButton detalleVerUsuarioButton;
    private javax.swing.JPasswordField detallejPasswordField;
    private javax.swing.JLabel detallepassLabel;
    private javax.swing.JTextField detalletelefonoTextField;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nuevoApellidoLabel;
    private javax.swing.JTextField nuevoApellidoTextField;
    private javax.swing.JButton nuevoCancelarButton;
    private javax.swing.JLabel nuevoConfirmarPasslLabel;
    private javax.swing.JPasswordField nuevoConfirmarjPasswordField;
    private javax.swing.JLabel nuevoContraseñaLabel;
    private javax.swing.JLabel nuevoDIreccionLabel;
    private javax.swing.JTextField nuevoDireccionTextField;
    private javax.swing.JLabel nuevoEmailLabel;
    private javax.swing.JTextField nuevoEmailTextField;
    private javax.swing.JLabel nuevoNombreLabel;
    private javax.swing.JTextField nuevoNombreTextField;
    private javax.swing.JLabel nuevoNombreUsuarioLabel;
    private javax.swing.JTextField nuevoNombreUsuarioTextField;
    private javax.swing.JLabel nuevoNumeroDocLabel;
    private javax.swing.JTextField nuevoNumeroDocTextField;
    private javax.swing.JButton nuevoRegistrarButton;
    private javax.swing.JLabel nuevoTIpoPersonaLabel;
    private javax.swing.JLabel nuevoTIpoUsuarioLabel1;
    private javax.swing.JLabel nuevoTelefonoLabel;
    private javax.swing.JComboBox<String> nuevoTipoDocJComboBox;
    private javax.swing.JLabel nuevoTipoDocULabel;
    private javax.swing.JComboBox<String> nuevoTipoPersonajComboBox;
    private javax.swing.JComboBox<String> nuevoTipoUsuariojComboBox;
    private javax.swing.JButton nuevoUsuarioButton;
    private javax.swing.JLabel nuevoUsuarioLabel;
    private javax.swing.JLabel nuevoValidacionLabel;
    private javax.swing.JPasswordField nuevojPasswordField;
    private javax.swing.JTextField nuevotelefonoTextField;
    private javax.swing.JPanel registroPanel;
    private javax.swing.JTable usuariosTable;
    // End of variables declaration//GEN-END:variables
}
