/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupo.view;

import java.awt.Color;

/**
 *
 * @author ccolome
 */
public class VentaPrueba extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramed
     */
    public VentaPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventaTabbedPane = new javax.swing.JTabbedPane();
        consultaPanel = new javax.swing.JPanel();
        consultaBuscarLabel = new javax.swing.JLabel();
        consultaBuscarTextField = new javax.swing.JTextField();
        nuevoVentaButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ventasTable = new javax.swing.JTable();
        detalleVerVentaButton = new javax.swing.JButton();
        registroPanel = new javax.swing.JPanel();
        nuevoVentaLabel = new javax.swing.JLabel();
        nuevoSelecionCliLabel = new javax.swing.JLabel();
        nuevoRegistrarButton = new javax.swing.JButton();
        nuevoCancelarButton = new javax.swing.JButton();
        nuevoValidacionLabel = new javax.swing.JLabel();
        nuevoSelectCliTextField = new javax.swing.JTextField();
        nuevoSerieTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        nuevoSelectClientejList = new javax.swing.JList<>();
        nuevoSeriejLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        nuevoProductosTable = new javax.swing.JTable();
        nuevoProductojLabel = new javax.swing.JLabel();
        nuevoSubTotaljLabel = new javax.swing.JLabel();
        nuevoTotaljLabel = new javax.swing.JLabel();
        nuevoIGVjLabel = new javax.swing.JLabel();
        nuevoComprobanteLabel = new javax.swing.JLabel();
        nuevoComprobanteComboBox = new javax.swing.JComboBox<>();
        nuevoProductojButton = new javax.swing.JButton();
        nuevoProductoEliminarjButton = new javax.swing.JButton();
        detallePanel = new javax.swing.JPanel();
        detalleVentaLabel = new javax.swing.JLabel();
        detalleSerieLabel = new javax.swing.JLabel();
        detalleSerieTextField = new javax.swing.JTextField();
        detalleCorrelativoTextField = new javax.swing.JTextField();
        detalleCorrelativoLabel = new javax.swing.JLabel();
        detalleSalirButton = new javax.swing.JButton();
        detalleComprobanteLabel = new javax.swing.JLabel();
        detalleNombreClienteTextField = new javax.swing.JTextField();
        detalleNombreClienteLabel = new javax.swing.JLabel();
        detalleDocClienteTextField = new javax.swing.JTextField();
        detalleDocClienteLabel = new javax.swing.JLabel();
        detalleProductojLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        detalleProductosTable = new javax.swing.JTable();
        detalleSubTotaljLabel = new javax.swing.JLabel();
        detalleIGVjLabel = new javax.swing.JLabel();
        detalleTotaljLabel = new javax.swing.JLabel();
        detalleComprobanteComboBox = new javax.swing.JComboBox<>();
        detalleImprimirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ventaTabbedPane.setMinimumSize(new java.awt.Dimension(620, 480));
        ventaTabbedPane.setPreferredSize(new java.awt.Dimension(620, 480));

        consultaBuscarLabel.setText("Buscar :");

        consultaBuscarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBuscarTextFieldActionPerformed(evt);
            }
        });

        nuevoVentaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        nuevoVentaButton.setText("Nuevo");
        nuevoVentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoVentaButtonActionPerformed(evt);
            }
        });

        ventasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Id Cliente", "Serie", "Correlativo", "Importe total", "Creador", "Creacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ventasTable);

        detalleVerVentaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        detalleVerVentaButton.setText("Venta N°");
        detalleVerVentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleVerVentaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaPanelLayout = new javax.swing.GroupLayout(consultaPanel);
        consultaPanel.setLayout(consultaPanelLayout);
        consultaPanelLayout.setHorizontalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addComponent(consultaBuscarLabel)
                        .addGap(18, 18, 18)
                        .addComponent(consultaBuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detalleVerVentaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuevoVentaButton)))
                .addContainerGap())
        );
        consultaPanelLayout.setVerticalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPanelLayout.createSequentialGroup()
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consultaBuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultaBuscarLabel)))
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevoVentaButton)
                            .addComponent(detalleVerVentaButton))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ventaTabbedPane.addTab("Consulta de ventas", consultaPanel);

        nuevoVentaLabel.setText("Nueva venta");

        nuevoSelecionCliLabel.setText("<html><body>Seleccione<br>cliente:</body></html>");

        nuevoRegistrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        nuevoRegistrarButton.setText("Registrar");
        nuevoRegistrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoRegistrarButtonActionPerformed(evt);
            }
        });

        nuevoCancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        nuevoCancelarButton.setText("Cancelar");
        nuevoCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCancelarButtonActionPerformed(evt);
            }
        });

        nuevoValidacionLabel.setBackground(new java.awt.Color(255, 0, 0));
        nuevoValidacionLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        nuevoValidacionLabel.setForeground(new java.awt.Color(255, 0, 0));
        nuevoValidacionLabel.setText("EL campo {} es obligatorio.");

        nuevoSelectCliTextField.setText("Buscar cliente");
        nuevoSelectCliTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nuevoSelectCliTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nuevoSelectCliTextFieldFocusLost(evt);
            }
        });
        nuevoSelectCliTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoSelectCliTextFieldActionPerformed(evt);
            }
        });

        nuevoSelectClientejList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        nuevoSelectClientejList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        nuevoSelectClientejList.setToolTipText("");
        jScrollPane1.setViewportView(nuevoSelectClientejList);

        nuevoSeriejLabel.setText("Serie:");

        nuevoProductosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Cantidad", "Precio", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(nuevoProductosTable);

        nuevoProductojLabel.setText("Productos:");

        nuevoSubTotaljLabel.setText("SubTotal:");

        nuevoTotaljLabel.setText("Total:");

        nuevoIGVjLabel.setText("I:G.V(18%):");

        nuevoComprobanteLabel.setText("Comprobante:");

        nuevoComprobanteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLETA", "FACTURA" }));

        nuevoProductojButton.setText("Agregar");
        nuevoProductojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProductojButtonActionPerformed(evt);
            }
        });

        nuevoProductoEliminarjButton.setText("Eliminar");
        nuevoProductoEliminarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProductoEliminarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registroPanelLayout = new javax.swing.GroupLayout(registroPanel);
        registroPanel.setLayout(registroPanelLayout);
        registroPanelLayout.setHorizontalGroup(
            registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelLayout.createSequentialGroup()
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevoSelecionCliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoSeriejLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addComponent(nuevoSerieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nuevoComprobanteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nuevoComprobanteComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nuevoSelectCliTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addComponent(nuevoVentaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(nuevoValidacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nuevoProductojLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroPanelLayout.createSequentialGroup()
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(nuevoProductoEliminarjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nuevoProductojButton))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nuevoSubTotaljLabel)
                            .addComponent(nuevoIGVjLabel)
                            .addComponent(nuevoTotaljLabel)
                            .addComponent(nuevoRegistrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(nuevoCancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        registroPanelLayout.setVerticalGroup(
            registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoVentaLabel)
                    .addComponent(nuevoValidacionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoSeriejLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nuevoSerieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nuevoComprobanteLabel)
                        .addComponent(nuevoComprobanteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addComponent(nuevoSelectCliTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(nuevoSelecionCliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoProductojLabel)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevoProductojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoProductoEliminarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addComponent(nuevoSubTotaljLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoIGVjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoTotaljLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nuevoRegistrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuevoCancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        ventaTabbedPane.addTab("Registro de venta", registroPanel);

        detalleVentaLabel.setText(" Detalle venta : N° ");

        detalleSerieLabel.setText("Serie:");

        detalleCorrelativoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleCorrelativoTextFieldActionPerformed(evt);
            }
        });

        detalleCorrelativoLabel.setText("Correlativo:");

        detalleSalirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        detalleSalirButton.setToolTipText("Salir");
        detalleSalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleSalirButtonActionPerformed(evt);
            }
        });

        detalleComprobanteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detalleComprobanteLabel.setText("Comprobante:");

        detalleNombreClienteLabel.setText("<html><body>Nombre<br>cliente:</body></html>");

        detalleDocClienteLabel.setText("<html><body>N° Doc<br>cliente:</body></html>");

        detalleProductojLabel.setText("Productos:");

        detalleProductosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Cantidad", "Precio", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(detalleProductosTable);

        detalleSubTotaljLabel.setText("SubTotal:");

        detalleIGVjLabel.setText("I:G.V(18%):");

        detalleTotaljLabel.setText("Total:");

        detalleComprobanteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLETA", "FACTURA" }));

        detalleImprimirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        detalleImprimirButton.setToolTipText("Salir");
        detalleImprimirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleImprimirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detallePanelLayout = new javax.swing.GroupLayout(detallePanel);
        detallePanel.setLayout(detallePanelLayout);
        detallePanelLayout.setHorizontalGroup(
            detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallePanelLayout.createSequentialGroup()
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detalleVentaLabel)
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addComponent(detalleSerieLabel)
                                .addGap(37, 37, 37)
                                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detallePanelLayout.createSequentialGroup()
                                        .addComponent(detalleSerieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(detalleCorrelativoLabel))
                                    .addGroup(detallePanelLayout.createSequentialGroup()
                                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(detalleDocClienteTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                            .addComponent(detalleNombreClienteTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(detalleComprobanteLabel)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detallePanelLayout.createSequentialGroup()
                                        .addComponent(detalleImprimirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(detalleSalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(detalleCorrelativoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(detalleComprobanteComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detallePanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(detalleSubTotaljLabel)
                                    .addComponent(detalleIGVjLabel)
                                    .addComponent(detalleTotaljLabel)))
                            .addComponent(detalleNombreClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detalleDocClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detalleProductojLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        detallePanelLayout.setVerticalGroup(
            detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detalleVentaLabel)
                    .addComponent(detalleSalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleImprimirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detalleSerieLabel)
                    .addComponent(detalleSerieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleCorrelativoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleCorrelativoLabel))
                .addGap(18, 18, 18)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detalleNombreClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleNombreClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleComprobanteLabel)
                    .addComponent(detalleComprobanteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detalleDocClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleDocClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detalleProductojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detallePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(detallePanelLayout.createSequentialGroup()
                        .addComponent(detalleSubTotaljLabel)
                        .addGap(18, 18, 18)
                        .addComponent(detalleIGVjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(detalleTotaljLabel)
                        .addGap(0, 145, Short.MAX_VALUE))))
        );

        ventaTabbedPane.addTab("Detalle de venta", detallePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventaTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventaTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaBuscarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBuscarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaBuscarTextFieldActionPerformed

    private void nuevoVentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoVentaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoVentaButtonActionPerformed

    private void nuevoRegistrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoRegistrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoRegistrarButtonActionPerformed

    private void nuevoCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoCancelarButtonActionPerformed

    private void detalleSalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleSalirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleSalirButtonActionPerformed

    private void detalleVerVentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleVerVentaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleVerVentaButtonActionPerformed

    private void detalleCorrelativoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleCorrelativoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleCorrelativoTextFieldActionPerformed

    private void nuevoSelectCliTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoSelectCliTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoSelectCliTextFieldActionPerformed

    private void nuevoSelectCliTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nuevoSelectCliTextFieldFocusGained
        if (nuevoSelectCliTextField.getText().equals("Buscar cliente")) {
            nuevoSelectCliTextField.setText("");
            nuevoSelectCliTextField.setForeground(Color.GRAY);
        }    }//GEN-LAST:event_nuevoSelectCliTextFieldFocusGained

    private void nuevoSelectCliTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nuevoSelectCliTextFieldFocusLost
        if (nuevoSelectCliTextField.getText().isEmpty()) {
            nuevoSelectCliTextField.setForeground(Color.GRAY);
            nuevoSelectCliTextField.setText("Buscar cliente");
        }
    }//GEN-LAST:event_nuevoSelectCliTextFieldFocusLost

    private void nuevoProductojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProductojButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoProductojButtonActionPerformed

    private void nuevoProductoEliminarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProductoEliminarjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoProductoEliminarjButtonActionPerformed

    private void detalleImprimirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleImprimirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleImprimirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consultaBuscarLabel;
    private javax.swing.JTextField consultaBuscarTextField;
    private javax.swing.JPanel consultaPanel;
    private javax.swing.JComboBox<String> detalleComprobanteComboBox;
    private javax.swing.JLabel detalleComprobanteLabel;
    private javax.swing.JLabel detalleCorrelativoLabel;
    private javax.swing.JTextField detalleCorrelativoTextField;
    private javax.swing.JLabel detalleDocClienteLabel;
    private javax.swing.JTextField detalleDocClienteTextField;
    private javax.swing.JLabel detalleIGVjLabel;
    private javax.swing.JButton detalleImprimirButton;
    private javax.swing.JLabel detalleNombreClienteLabel;
    private javax.swing.JTextField detalleNombreClienteTextField;
    private javax.swing.JPanel detallePanel;
    private javax.swing.JLabel detalleProductojLabel;
    private javax.swing.JTable detalleProductosTable;
    private javax.swing.JButton detalleSalirButton;
    private javax.swing.JLabel detalleSerieLabel;
    private javax.swing.JTextField detalleSerieTextField;
    private javax.swing.JLabel detalleSubTotaljLabel;
    private javax.swing.JLabel detalleTotaljLabel;
    private javax.swing.JLabel detalleVentaLabel;
    private javax.swing.JButton detalleVerVentaButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton nuevoCancelarButton;
    private javax.swing.JComboBox<String> nuevoComprobanteComboBox;
    private javax.swing.JLabel nuevoComprobanteLabel;
    private javax.swing.JLabel nuevoIGVjLabel;
    private javax.swing.JButton nuevoProductoEliminarjButton;
    private javax.swing.JButton nuevoProductojButton;
    private javax.swing.JLabel nuevoProductojLabel;
    private javax.swing.JTable nuevoProductosTable;
    private javax.swing.JButton nuevoRegistrarButton;
    private javax.swing.JLabel nuevoSelecionCliLabel;
    private javax.swing.JTextField nuevoSelectCliTextField;
    private javax.swing.JList<String> nuevoSelectClientejList;
    private javax.swing.JTextField nuevoSerieTextField;
    private javax.swing.JLabel nuevoSeriejLabel;
    private javax.swing.JLabel nuevoSubTotaljLabel;
    private javax.swing.JLabel nuevoTotaljLabel;
    private javax.swing.JLabel nuevoValidacionLabel;
    private javax.swing.JButton nuevoVentaButton;
    private javax.swing.JLabel nuevoVentaLabel;
    private javax.swing.JPanel registroPanel;
    private javax.swing.JTabbedPane ventaTabbedPane;
    private javax.swing.JTable ventasTable;
    // End of variables declaration//GEN-END:variables
}
