/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupo.view;

/**
 *
 * @author ccolome
 */
public class VentaProductoPrueba extends javax.swing.JFrame {

    /**
     * Creates new form f
     */
    public VentaProductoPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoVentaProductoPanel = new javax.swing.JPanel();
        nuevoSeleccionProdLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nuevoProductojList = new javax.swing.JList<>();
        nuevoCantidadSpinner = new javax.swing.JSpinner();
        nuevoCantidadJLabel = new javax.swing.JLabel();
        nuevoAgregarProdjButton = new javax.swing.JButton();
        nuevoSelectProductoTextField = new javax.swing.JTextField();
        nuevoVentaProductoValidaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevoSeleccionProdLabel.setText("<html><body>Seleccione<br>producto:</body></html>");

        nuevoProductojList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        nuevoProductojList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        nuevoProductojList.setToolTipText("");
        jScrollPane1.setViewportView(nuevoProductojList);

        nuevoCantidadSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        nuevoCantidadJLabel.setText("Cantidad:");

        nuevoAgregarProdjButton.setText("Agregar");
        nuevoAgregarProdjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAgregarProdjButtonActionPerformed(evt);
            }
        });

        nuevoSelectProductoTextField.setText("Buscar Producto");
        nuevoSelectProductoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoSelectProductoTextFieldActionPerformed(evt);
            }
        });

        nuevoVentaProductoValidaLabel.setBackground(new java.awt.Color(255, 0, 0));
        nuevoVentaProductoValidaLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        nuevoVentaProductoValidaLabel.setForeground(new java.awt.Color(255, 0, 0));
        nuevoVentaProductoValidaLabel.setText("EL campo {} es obligatorio.");

        javax.swing.GroupLayout nuevoVentaProductoPanelLayout = new javax.swing.GroupLayout(nuevoVentaProductoPanel);
        nuevoVentaProductoPanel.setLayout(nuevoVentaProductoPanelLayout);
        nuevoVentaProductoPanelLayout.setHorizontalGroup(
            nuevoVentaProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoVentaProductoPanelLayout.createSequentialGroup()
                .addGroup(nuevoVentaProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoVentaProductoPanelLayout.createSequentialGroup()
                        .addGroup(nuevoVentaProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nuevoVentaProductoPanelLayout.createSequentialGroup()
                                .addComponent(nuevoCantidadJLabel)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoVentaProductoPanelLayout.createSequentialGroup()
                                .addComponent(nuevoSeleccionProdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(nuevoVentaProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(nuevoSelectProductoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(nuevoCantidadSpinner)))
                    .addGroup(nuevoVentaProductoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nuevoAgregarProdjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuevoVentaProductoValidaLabel)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        nuevoVentaProductoPanelLayout.setVerticalGroup(
            nuevoVentaProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoVentaProductoPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(nuevoVentaProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevoSeleccionProdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nuevoVentaProductoPanelLayout.createSequentialGroup()
                        .addComponent(nuevoSelectProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(nuevoVentaProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoCantidadJLabel)
                    .addComponent(nuevoCantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(nuevoVentaProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoAgregarProdjButton)
                    .addComponent(nuevoVentaProductoValidaLabel))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoVentaProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoVentaProductoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoAgregarProdjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAgregarProdjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoAgregarProdjButtonActionPerformed

    private void nuevoSelectProductoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoSelectProductoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoSelectProductoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaProductoPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaProductoPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaProductoPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaProductoPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaProductoPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevoAgregarProdjButton;
    private javax.swing.JLabel nuevoCantidadJLabel;
    private javax.swing.JSpinner nuevoCantidadSpinner;
    private javax.swing.JList<String> nuevoProductojList;
    private javax.swing.JLabel nuevoSeleccionProdLabel;
    private javax.swing.JTextField nuevoSelectProductoTextField;
    private javax.swing.JPanel nuevoVentaProductoPanel;
    private javax.swing.JLabel nuevoVentaProductoValidaLabel;
    // End of variables declaration//GEN-END:variables
}
